// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYRGZ3B06EmhXF7fWAZsEdGyoye462vBY',
    appId: '1:423965435950:web:1199d92157dee1a0ba97bf',
    messagingSenderId: '423965435950',
    projectId: 'attendance-a82ae',
    authDomain: 'attendance-a82ae.firebaseapp.com',
    storageBucket: 'attendance-a82ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUNkjVaUguQ1Ps8D8-l-5ajJxTt7i8iI',
    appId: '1:423965435950:android:1986db8c545ce27aba97bf',
    messagingSenderId: '423965435950',
    projectId: 'attendance-a82ae',
    storageBucket: 'attendance-a82ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdCmsQxWUfo1rnz8zqty7_8UJmZh7zsbQ',
    appId: '1:423965435950:ios:41495be1e59abafeba97bf',
    messagingSenderId: '423965435950',
    projectId: 'attendance-a82ae',
    storageBucket: 'attendance-a82ae.firebasestorage.app',
    iosBundleId: 'com.example.attendanceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdCmsQxWUfo1rnz8zqty7_8UJmZh7zsbQ',
    appId: '1:423965435950:ios:41495be1e59abafeba97bf',
    messagingSenderId: '423965435950',
    projectId: 'attendance-a82ae',
    storageBucket: 'attendance-a82ae.firebasestorage.app',
    iosBundleId: 'com.example.attendanceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYRGZ3B06EmhXF7fWAZsEdGyoye462vBY',
    appId: '1:423965435950:web:0b0fb818b3996b8bba97bf',
    messagingSenderId: '423965435950',
    projectId: 'attendance-a82ae',
    authDomain: 'attendance-a82ae.firebaseapp.com',
    storageBucket: 'attendance-a82ae.firebasestorage.app',
  );
}
